Improvements

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -13,7 +13,7 @@ inputs:
 
   path:
     description: "Path to directory with sources"
-    required: true
+    required: false
 
   version:
     description: "Version of Goveralls"
@@ -44,7 +44,23 @@ runs:
       uses: actions/cache@v3
       with:
         path: ~/.cache/goveralls
-        key: ${{runner.os}}-ek-goveralls-action-v${{inputs.version}}
+        key: ${{runner.os}}-ek-goveralls-action-${{inputs.version}}
+
+    - id: goveralls-validate-options
+      name: Options validation
+      shell: bash
+      run: |
+        # [goveralls-validate-options]
+
+        if [[ ! -f "${{inputs.profile}}" ]] ; then
+          echo "::error::Profile ${{inputs.profile}} doesn't exist"
+          exit 1
+        fi
+
+        if [[ -n "${{inputs.path}}" && ! -d "${{inputs.path}}" ]] ; then
+          echo "::error::Directory ${{inputs.path}} doesn't exist"
+          exit 1
+        fi
 
     - id: goveralls-install
       name: Install Goveralls
@@ -53,9 +69,21 @@ runs:
       run: |
         # [goveralls-install]
 
-        echo -e "::group::\033[34mInstalling Goveralls…\033[0m"
+        version=${{inputs.version}}
+
+        if [[ "$version" != "latest" ]] ; then
+          version="v$version"
+        fi
+
+        echo -e "::group::\033[34mInstalling Goveralls ($version)…\033[0m"
+
         mkdir -p ~/.cache
-        go install "github.com/mattn/goveralls@v${{inputs.version}}"
+        if ! go install "github.com/mattn/goveralls@$version" ; then
+          echo "::endgroup::"
+          echo "::error::Can't download goveralls (version: $version)"
+          exit 1
+        fi
+
         echo "::endgroup::"
 
         cp "$(go env GOPATH)/bin/goveralls" ~/.cache/goveralls
@@ -114,5 +142,8 @@ runs:
           echo -e "\033[34mFinishing parallel test…\033[0m"
         fi
 
-        cd ${{inputs.path}}
+        if [[ -n "${{inputs.path}}" ]] ; then
+          cd ${{inputs.path}}
+        fi
+
         ~/.cache/goveralls ${{steps.goveralls-set-options.outputs.options}}
